name: CI

on:
  push:
  pull_request:

jobs:
  linux-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
        with:
          version: 11.7.0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.19.0
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check

  windows-checks:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
        with:
          version: 11.7.0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.19.0
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check
